module.exports = {
  christianAlfoni: require("./christian-alfoni"),
  davidKhourshid: require("./david-khourshid"),
  gantLaborde: require("./gant-laborde"),
  janiEvakallio: require("./jani-evakallio"),
  kasiaJastrzebska: require("./kasia-jastrzebska"),
  kenWheeler: require("./ken-wheeler"),
  nikGraf: require("./nik-graf"),
  michelWeststrate: require("./michel-weststrate"),
  patrickStapfer: require("./patrick-stapfer"),
  rotemMizrachiMeidan: require("./rotem-mizrachi-meidan"),
  saraVieira: require("./sara-vieira"),
  shayKeinan: require("./shay-keinan"),
  siaKaramalegos: require("./sia-karamalegos"),
  varyaStepanova: require("./varya-stepanova"),
};
