module.exports = [
  require("./agent-conf"),
  require("./gofore"),
  require("./half-stack"),
  require("./nitor"),
  require("./motley"),
  require("./react-alicante"),
  require("./react-day-berlin"),
  require("./react-fest"),
  require("./react-native-eu"),
  require("./reason-conf"),
  require("./rohea"),
  require("./solita"),
  require("./survivejs"),
  require("./webexpo"),
];
