module.exports = {
  andreyOkonetchnikov: require("./andrey-okonetchnikov"),
  artemSapegin: require("./artem-sapegin"),
  christianAlfoni: require("./christian-alfoni"),
  davidKhourshid: require("./david-khourshid"),
  gantLaborde: require("./gant-laborde"),
  janiEvakallio: require("./jani-evakallio"),
  juhoVepsalainen: require("./juho-vepsalainen"),
  kasiaJastrzebska: require("./kasia-jastrzebska"),
  kenWheeler: require("./ken-wheeler"),
  michelWeststrate: require("./michel-weststrate"),
  nikGraf: require("./nik-graf"),
  patrickStapfer: require("./patrick-stapfer"),
  rotemMizrachiMeidan: require("./rotem-mizrachi-meidan"),
  saraVieira: require("./sara-vieira"),
  shayKeinan: require("./shay-keinan"),
  siaKaramalegos: require("./sia-karamalegos"),
  svenSauleau: require("./sven-sauleau"),
  varyaStepanova: require("./varya-stepanova"),
};
