module.exports = {
  BABEL: "Babel",
  CEREBRAL: "Cerebral",
  DETOX: "Detox",
  IMMER: "Immer",
  NEXT_JS: "Next.js",
  MOBX: "MobX",
  MOBX_STATE_TREE: "mobx-state-tree",
  REACT: "React",
  REACT_NATIVE: "React Native",
  REACT_VR: "React VR",
  REASON: "Reason",
  SSR: "Server Side Rendering",
  STATE_MANAGEMENT: "State management",
  STYLING: "Styling",
  STYLEGUIDIST: "Styleguidist",
  STYLE_GUIDES: "Style guides",
  TESTING: "Testing",
  TOOLING: "Tooling",
  UNIVERSAL_REACT: "Universal React",
  WEBPACK: "Webpack",
};
